// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWA.Data.Context;

#nullable disable

namespace TWA.Data.Migrations
{
    [DbContext(typeof(TwaDbContext))]
    [Migration("20260114204849_AddBuildQueueJson")]
    partial class AddBuildQueueJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWA.Core.Entities.AttackTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroqNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceVillageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetPlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetX")
                        .HasColumnType("int");

                    b.Property<int>("TargetY")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceVillageId");

                    b.ToTable("AttackTasks");
                });

            modelBuilder.Entity("TWA.Core.Entities.BuildingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("BuildingPlans");
                });

            modelBuilder.Entity("TWA.Core.Entities.DailyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("TWA.Core.Entities.ScheduledOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("bit");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScheduledOperations");
                });

            modelBuilder.Entity("TWA.Core.Entities.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademyLevel")
                        .HasColumnType("int");

                    b.Property<string>("AiAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableMerchants")
                        .HasColumnType("int");

                    b.Property<int>("BarracksLevel")
                        .HasColumnType("int");

                    b.Property<string>("BuildQueueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuildingBarracks")
                        .HasColumnType("int");

                    b.Property<int>("BuildingFarm")
                        .HasColumnType("int");

                    b.Property<int>("BuildingGarage")
                        .HasColumnType("int");

                    b.Property<int>("BuildingIron")
                        .HasColumnType("int");

                    b.Property<int>("BuildingMain")
                        .HasColumnType("int");

                    b.Property<int>("BuildingSmithy")
                        .HasColumnType("int");

                    b.Property<int>("BuildingSnob")
                        .HasColumnType("int");

                    b.Property<int>("BuildingStable")
                        .HasColumnType("int");

                    b.Property<int>("BuildingStone")
                        .HasColumnType("int");

                    b.Property<int>("BuildingStorage")
                        .HasColumnType("int");

                    b.Property<int>("BuildingWall")
                        .HasColumnType("int");

                    b.Property<int>("BuildingWood")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Iron")
                        .HasColumnType("int");

                    b.Property<int>("IronHourly")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Loyalty")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PopulationCurrent")
                        .HasColumnType("int");

                    b.Property<int>("PopulationMax")
                        .HasColumnType("int");

                    b.Property<int>("SmithyLevel")
                        .HasColumnType("int");

                    b.Property<int>("StableLevel")
                        .HasColumnType("int");

                    b.Property<int>("Stone")
                        .HasColumnType("int");

                    b.Property<int>("StoneHourly")
                        .HasColumnType("int");

                    b.Property<int>("StorageCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TargetArcher")
                        .HasColumnType("int");

                    b.Property<int>("TargetAxe")
                        .HasColumnType("int");

                    b.Property<int>("TargetCatapult")
                        .HasColumnType("int");

                    b.Property<int>("TargetHeavy")
                        .HasColumnType("int");

                    b.Property<int>("TargetKnight")
                        .HasColumnType("int");

                    b.Property<int>("TargetLight")
                        .HasColumnType("int");

                    b.Property<int>("TargetMarcher")
                        .HasColumnType("int");

                    b.Property<int>("TargetRam")
                        .HasColumnType("int");

                    b.Property<int>("TargetSnob")
                        .HasColumnType("int");

                    b.Property<int>("TargetSpear")
                        .HasColumnType("int");

                    b.Property<int>("TargetSpy")
                        .HasColumnType("int");

                    b.Property<int>("TargetSword")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WallLevel")
                        .HasColumnType("int");

                    b.Property<int>("Wood")
                        .HasColumnType("int");

                    b.Property<int>("WoodHourly")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("TWA.Core.Entities.WorldConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArchersActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FakeLimitPercent")
                        .HasColumnType("int");

                    b.Property<double>("GameSpeed")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LagRandomizationMs")
                        .HasColumnType("int");

                    b.Property<bool>("MillisecondsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("NightBonusActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("NightEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("NightStart")
                        .HasColumnType("time");

                    b.Property<bool>("PaladinActive")
                        .HasColumnType("bit");

                    b.Property<double>("UnitSpeed")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorldConfigs");
                });

            modelBuilder.Entity("TWA.Core.Entities.AttackTask", b =>
                {
                    b.HasOne("TWA.Core.Entities.Village", "SourceVillage")
                        .WithMany("Attacks")
                        .HasForeignKey("SourceVillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TWA.Core.Entities.TroopSet", "Troops", b1 =>
                        {
                            b1.Property<int>("AttackTaskId")
                                .HasColumnType("int");

                            b1.Property<int>("Axe")
                                .HasColumnType("int");

                            b1.Property<int>("Catapult")
                                .HasColumnType("int");

                            b1.Property<int>("Heavy")
                                .HasColumnType("int");

                            b1.Property<int>("Knight")
                                .HasColumnType("int");

                            b1.Property<int>("Light")
                                .HasColumnType("int");

                            b1.Property<int>("Militia")
                                .HasColumnType("int");

                            b1.Property<int>("Ram")
                                .HasColumnType("int");

                            b1.Property<int>("Snob")
                                .HasColumnType("int");

                            b1.Property<int>("Spear")
                                .HasColumnType("int");

                            b1.Property<int>("Spy")
                                .HasColumnType("int");

                            b1.Property<int>("Sword")
                                .HasColumnType("int");

                            b1.HasKey("AttackTaskId");

                            b1.ToTable("AttackTasks");

                            b1.WithOwner()
                                .HasForeignKey("AttackTaskId");
                        });

                    b.Navigation("SourceVillage");

                    b.Navigation("Troops")
                        .IsRequired();
                });

            modelBuilder.Entity("TWA.Core.Entities.BuildingPlan", b =>
                {
                    b.HasOne("TWA.Core.Entities.Village", "Village")
                        .WithMany("BuildQueue")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("TWA.Core.Entities.DailyTask", b =>
                {
                    b.HasOne("TWA.Core.Entities.Village", null)
                        .WithMany("DailyTasks")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWA.Core.Entities.Village", b =>
                {
                    b.OwnsOne("TWA.Core.Entities.TroopSet", "OwnedTroops", b1 =>
                        {
                            b1.Property<int>("VillageId")
                                .HasColumnType("int");

                            b1.Property<int>("Axe")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Axe");

                            b1.Property<int>("Catapult")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Catapult");

                            b1.Property<int>("Heavy")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Heavy");

                            b1.Property<int>("Knight")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Knight");

                            b1.Property<int>("Light")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Light");

                            b1.Property<int>("Militia")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Militia");

                            b1.Property<int>("Ram")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Ram");

                            b1.Property<int>("Snob")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Snob");

                            b1.Property<int>("Spear")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Spear");

                            b1.Property<int>("Spy")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Spy");

                            b1.Property<int>("Sword")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Own_Sword");

                            b1.HasKey("VillageId");

                            b1.ToTable("Villages");

                            b1.WithOwner()
                                .HasForeignKey("VillageId");
                        });

                    b.OwnsOne("TWA.Core.Entities.TroopSet", "TotalTroops", b1 =>
                        {
                            b1.Property<int>("VillageId")
                                .HasColumnType("int");

                            b1.Property<int>("Axe")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Axe");

                            b1.Property<int>("Catapult")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Catapult");

                            b1.Property<int>("Heavy")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Heavy");

                            b1.Property<int>("Knight")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Knight");

                            b1.Property<int>("Light")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Light");

                            b1.Property<int>("Militia")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Militia");

                            b1.Property<int>("Ram")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Ram");

                            b1.Property<int>("Snob")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Snob");

                            b1.Property<int>("Spear")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Spear");

                            b1.Property<int>("Spy")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Spy");

                            b1.Property<int>("Sword")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("Total_Sword");

                            b1.HasKey("VillageId");

                            b1.ToTable("Villages");

                            b1.WithOwner()
                                .HasForeignKey("VillageId");
                        });

                    b.Navigation("OwnedTroops")
                        .IsRequired();

                    b.Navigation("TotalTroops")
                        .IsRequired();
                });

            modelBuilder.Entity("TWA.Core.Entities.Village", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("BuildQueue");

                    b.Navigation("DailyTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
